libsel4-sys = {git = "ssh://github.com/PolySync/libsel4-sys.git", branch = "devel"}

[dependencies.wee_alloc]
version = "0.4"
features = ["static_array_backend"]

[dependencies.proptest]
version = "0.7"
default-features = false
features = ["alloc", "nightly"]

[features]
default = []
alloc = []
